# Generated by Django 2.2.12 on 2020-09-12 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('latitude', models.FloatField(help_text='Latitude of house in range (-90 to 90)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude of house in range (-180 to 180)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('price', models.FloatField(help_text='Price of house', validators=[django.core.validators.MinValueValidator(1)])),
                ('bedrooms', models.IntegerField(help_text='Number of Bedrooms', validators=[django.core.validators.MinValueValidator(1)])),
                ('bathrooms', models.IntegerField(help_text='Number of Bathrooms', validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.CheckConstraint(check=models.Q(latitude__range=(-90, 90)), name='valid_latitude_constraint'),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.CheckConstraint(check=models.Q(longitude__range=(-180, 180)), name='valid_longitude_constraint'),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.CheckConstraint(check=models.Q(price__gte=1), name='valid_price_constraint'),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.CheckConstraint(check=models.Q(bedrooms__gt=0), name='valid_bedrooms_constraints'),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.CheckConstraint(check=models.Q(bathrooms__gt=0), name='valid_bathrooms_constraints'),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('longitude', 'latitude')},
        ),
    ]
